import type {
  PublicClinicSummaryResponse,
  PublicDoctorSummaryResponse,
  PublicHospitalSummaryResponse,
} from "../../api/publicCatalog";

// Temporary local/UAT layout data.
// Must not be used by public catalog, search, booking, or production APIs.

export const demoDoctors: PublicDoctorSummaryResponse[] = [
  {
    publicDoctorId: "demo-doctor-neha-sharma",
    doctorSlug: "demo-neha-sharma",
    doctorDisplayName: "Dr. Neha Sharma",
    photoUrl: null,
    speciality: "Dermatology",
    yearsOfExperience: 8,
    consultationFee: 800,
    languages: ["English", "Hindi"],
    clinicDisplayName: "Kalyani Nagar Skin & Care",
    clinicSlug: "demo-kalyani-nagar-skin-care",
    area: "Kalyani Nagar",
    city: "Pune",
    subtitle: "Dermatologist",
    summary: "Skin consultation and preventive care for everyday concerns.",
    availableToday: true,
    nextAvailableSlotSummary: "Available today",
    distanceKm: 1.8,
  },
  {
    publicDoctorId: "demo-doctor-ravi-patil",
    doctorSlug: "demo-ravi-patil",
    doctorDisplayName: "Dr. Ravi Patil",
    photoUrl: null,
    speciality: "Cardiology",
    yearsOfExperience: 15,
    consultationFee: 1200,
    languages: ["English", "Hindi", "Marathi"],
    clinicDisplayName: "Hinjewadi Heart Centre",
    clinicSlug: "demo-hinjewadi-heart-centre",
    area: "Hinjewadi",
    city: "Pune",
    subtitle: "Cardiologist",
    summary: "Heart and lifestyle consultations for ongoing care planning.",
    availableToday: false,
    nextAvailableSlotSummary: "Next slot 11:30 AM",
    distanceKm: 4.2,
  },
  {
    publicDoctorId: "demo-doctor-priya-deshmukh",
    doctorSlug: "demo-priya-deshmukh",
    doctorDisplayName: "Dr. Priya Deshmukh",
    photoUrl: null,
    speciality: "Pediatrics",
    yearsOfExperience: 10,
    consultationFee: 900,
    languages: ["English", "Hindi"],
    clinicDisplayName: "Baner Child Care",
    clinicSlug: "demo-baner-child-care",
    area: "Baner",
    city: "Pune",
    subtitle: "Pediatrician",
    summary: "Family-friendly pediatric care for routine and follow-up visits.",
    availableToday: true,
    nextAvailableSlotSummary: "Available today",
    distanceKm: 5.5,
  },
];

export const demoClinics: PublicClinicSummaryResponse[] = [
  {
    clinicSlug: "demo-jeevanam-medical-centre",
    clinicDisplayName: "Jeevanam Medical Centre",
    logoUrl: null,
    coverUrl: null,
    address: "FC Road, Pune",
    area: "FC Road",
    city: "Pune",
    doctorsCount: 8,
    serviceCount: 6,
    departmentCount: 4,
    galleryCount: 3,
    emergencyAvailable: false,
    subtitle: "Multi-doctor clinic",
    summary: "Primary care and specialist consultations in one connected location.",
    availableToday: true,
    distanceKm: 1.2,
    specialities: ["General Physician", "Dermatology", "Pediatrics"],
  },
  {
    clinicSlug: "demo-care-and-cure-clinic",
    clinicDisplayName: "Care & Cure Clinic",
    logoUrl: null,
    coverUrl: null,
    address: "Baner, Pune",
    area: "Baner",
    city: "Pune",
    doctorsCount: 6,
    serviceCount: 5,
    departmentCount: 3,
    galleryCount: 2,
    emergencyAvailable: false,
    subtitle: "Neighbourhood clinic",
    summary: "Consultations, follow-ups and regular care with familiar clinicians.",
    availableToday: true,
    distanceKm: 2.9,
    specialities: ["Family Medicine", "ENT", "General Surgery"],
  },
  {
    clinicSlug: "demo-healthfirst-clinic",
    clinicDisplayName: "HealthFirst Clinic",
    logoUrl: null,
    coverUrl: null,
    address: "Kothrud, Pune",
    area: "Kothrud",
    city: "Pune",
    doctorsCount: 10,
    serviceCount: 7,
    departmentCount: 5,
    galleryCount: 4,
    emergencyAvailable: false,
    subtitle: "Clinic and diagnostics",
    summary: "Accessible clinic care with imaging and diagnostics support.",
    availableToday: true,
    distanceKm: 6.3,
    specialities: ["Diagnostics", "Orthopedics", "Gynecology"],
  },
];

export const demoHospitals: PublicHospitalSummaryResponse[] = [
  {
    hospitalSlug: "demo-jeevanam-multispeciality-hospital",
    hospitalDisplayName: "Jeevanam Multispeciality Hospital",
    logoUrl: null,
    coverUrl: null,
    area: "Shivajinagar",
    city: "Pune",
    doctorsCount: 42,
    serviceCount: 18,
    departmentCount: 12,
    galleryCount: 5,
    emergencyAvailable: false,
    departments: ["General Medicine", "Cardiology", "Orthopedics"],
    subtitle: "Multi-speciality care",
    summary: "Comprehensive hospital care with connected departments and teams.",
    distanceKm: 2.1,
  },
  {
    hospitalSlug: "demo-aarogya-hospital",
    hospitalDisplayName: "Aarogya Hospital",
    logoUrl: null,
    coverUrl: null,
    area: "Baner",
    city: "Pune",
    doctorsCount: 36,
    serviceCount: 14,
    departmentCount: 10,
    galleryCount: 4,
    emergencyAvailable: false,
    departments: ["Pediatrics", "Gynecology", "General Surgery"],
    subtitle: "Speciality hospital",
    summary: "Specialist-led care with diagnostics and outpatient services.",
    distanceKm: 4.8,
  },
  {
    hospitalSlug: "demo-citycare-hospital",
    hospitalDisplayName: "CityCare Hospital",
    logoUrl: null,
    coverUrl: null,
    area: "Kothrud",
    city: "Pune",
    doctorsCount: 30,
    serviceCount: 12,
    departmentCount: 9,
    galleryCount: 3,
    emergencyAvailable: false,
    departments: ["Internal Medicine", "ENT", "Dermatology"],
    subtitle: "Accessible hospital",
    summary: "Hospital care with a broad outpatient and diagnostics mix.",
    distanceKm: 6.7,
  },
];
