const env = import.meta.env;

export const branding = {
  productName: env.VITE_PRODUCT_NAME?.trim() || "Jeevanam Healthcare",
  tagline: env.VITE_PRODUCT_TAGLINE?.trim() || "Intelligent Healthcare Platform",
  companyName: env.VITE_COMPANY_NAME?.trim() || "DeepThoughtNet",
  aiPlatformName: env.VITE_AI_PLATFORM_NAME?.trim() || "AIVA",
};

export function productTitle() {
  return `${branding.productName} | ${branding.tagline}`;
}

export function generatedByLine() {
  return `Generated by ${branding.productName}`;
}

export function poweredByLine() {
  return `Powered by ${branding.aiPlatformName}`;
}

export function footerBrandingLine() {
  return `${branding.productName} · ${branding.tagline} · Powered by ${branding.aiPlatformName}`;
}
