package com.deepthoughtnet.clinic.api.lab.dto;

import com.deepthoughtnet.clinic.billing.service.model.BillStatus;
import com.deepthoughtnet.clinic.api.lab.db.LabOrderOrigin;
import com.deepthoughtnet.clinic.api.lab.service.model.LabOrderStatusRecord;
import com.deepthoughtnet.clinic.api.lab.service.model.LabSampleStatusRecord;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;

public record LabOrderResponse(
        String id,
        String tenantId,
        String orderNumber,
        String patientId,
        String patientNumber,
        String patientName,
        String doctorUserId,
        String doctorName,
        String consultationId,
        LabOrderOrigin orderOrigin,
        String requestedByInternalDoctorId,
        String externalDoctorName,
        String externalDoctorMobile,
        String externalClinicName,
        String referralSource,
        String notes,
        LabOrderStatusRecord status,
        OffsetDateTime orderedAt,
        String billId,
        String billNumber,
        BillStatus billStatus,
        BigDecimal billTotalAmount,
        BigDecimal billDueAmount,
        String externalLabVendor,
        String externalReferenceNumber,
        OffsetDateTime deliveredAt,
        String deliveredByUserId,
        OffsetDateTime paymentCollectedAt,
        OffsetDateTime readyForCollectionAt,
        String sampleAccessionNumber,
        String sampleBarcodeValue,
        LabSampleStatusRecord sampleSummaryStatus,
        String sampleType,
        OffsetDateTime sampleCollectedAt,
        String sampleCollectedByUserId,
        String sampleCollectedBy,
        String sampleCollectionNotes,
        OffsetDateTime processingStartedAt,
        OffsetDateTime resultEnteredAt,
        String resultComments,
        OffsetDateTime reportGeneratedAt,
        String reportGeneratedByUserId,
        String reportGeneratedBy,
        String reportFilename,
        OffsetDateTime reportPublishedAt,
        String reportPublishedByUserId,
        String reportDeliveryStatus,
        List<String> reportDeliveryChannels,
        String reportDeliveryNotes,
        OffsetDateTime doctorReviewedAt,
        String doctorReviewedByUserId,
        String doctorReviewedBy,
        String doctorReviewDecision,
        String doctorReviewReason,
        String doctorComments,
        OffsetDateTime labVerifiedAt,
        String labVerifiedBy,
        String labVerifiedByName,
        String labVerificationDecision,
        String labVerificationComments,
        String labVerificationReason,
        List<LabOrderAttachmentResponse> attachments,
        List<LabOrderItemResponse> items,
        List<LabSampleResponse> samples,
        List<LabOrderResultResponse> results,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {
    public record LabOrderAttachmentResponse(
            String id,
            String labOrderId,
            String attachmentType,
            String originalFilename,
            String mediaType,
            String storageKey,
            Long sizeBytes,
            String checksumSha256,
            String dicomMetadataJson,
            String uploadedByUserId,
            OffsetDateTime createdAt
    ) {
    }
}
