package com.deepthoughtnet.clinic.vaccination.service.model;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record PatientVaccinationRecord(
        UUID id,
        UUID tenantId,
        UUID patientId,
        String patientNumber,
        String patientName,
        String patientMobile,
        Integer patientAgeYears,
        String patientGender,
        String patientAllergies,
        UUID vaccineId,
        String vaccineName,
        String source,
        String externalPlace,
        UUID proofDocumentId,
        String verifiedStatus,
        UUID verifiedByUserId,
        String verifiedByUserName,
        OffsetDateTime verifiedAt,
        Integer doseNumber,
        LocalDate givenDate,
        LocalDate nextDueDate,
        String batchNumber,
        String notes,
        UUID administeredByUserId,
        String administeredByUserName,
        UUID createdByUserId,
        String createdByUserName,
        UUID updatedByUserId,
        String updatedByUserName,
        OffsetDateTime updatedAt,
        UUID billId,
        String billNumber,
        String billStatus,
        UUID billLineId,
        UUID inventoryTransactionId,
        UUID inventoryStockBatchId,
        String inventoryBatchNumber,
        String inventoryBatchManufacturer,
        LocalDate inventoryBatchExpiryDate,
        UUID reminderNotificationId,
        OffsetDateTime reminderQueuedAt,
        String reminderStatus,
        List<String> workflowWarnings,
        UUID recordedByUserId,
        String recordedByUserName,
        OffsetDateTime createdAt
) {
}
