package com.deepthoughtnet.clinic.api.publicsite.dto;

import java.util.List;

public record PublicDoctorDetailResponse(
        String publicDoctorId,
        String doctorSlug,
        String canonicalSlug,
        String publicPath,
        String doctorDisplayName,
        String photoUrl,
        String bookingMode,
        String qualification,
        String medicalCouncil,
        Integer yearsOfExperience,
        String summary,
        String biography,
        List<String> specialities,
        List<String> subSpecialities,
        List<String> languages,
        List<String> consultationModes,
        List<String> services,
        List<PublicProviderLocationResponse> locations,
        List<String> galleryImageUrls,
        String coverUrl,
        String logoUrl,
        String contactPhone,
        String contactEmail,
        String website,
        String area,
        String city,
        String state,
        String country,
        String primarySpeciality,
        java.math.BigDecimal consultationFee,
        boolean reviewsComingSoon,
        String subtitle,
        String bookingSummary,
        List<PublicPracticeMiniResponse> practices,
        List<PublicClinicMiniResponse> clinics,
        List<String> availableDays,
        List<String> nextAvailableSlots,
        boolean availableToday,
        String bookingReference,
        boolean canBookOnline
) {
    public PublicDoctorDetailResponse(
            String publicDoctorId,
            String doctorSlug,
            String canonicalSlug,
            String publicPath,
            String doctorDisplayName,
            String photoUrl,
            String bookingMode,
            String qualification,
            String medicalCouncil,
            Integer yearsOfExperience,
            String summary,
            String biography,
            List<String> specialities,
            List<String> subSpecialities,
            List<String> languages,
            List<String> consultationModes,
            List<String> services,
            List<PublicProviderLocationResponse> locations,
            List<String> galleryImageUrls,
            String coverUrl,
            String logoUrl,
            String contactPhone,
            String contactEmail,
            String website,
            String area,
            String city,
            String state,
            String country,
            String primarySpeciality,
            java.math.BigDecimal consultationFee,
            boolean reviewsComingSoon,
            String subtitle,
            String bookingSummary,
            List<PublicPracticeMiniResponse> practices,
            List<PublicClinicMiniResponse> clinics,
            List<String> availableDays,
            List<String> nextAvailableSlots,
            boolean availableToday
    ) {
        this(
                publicDoctorId,
                doctorSlug,
                canonicalSlug,
                publicPath,
                doctorDisplayName,
                photoUrl,
                bookingMode,
                qualification,
                medicalCouncil,
                yearsOfExperience,
                summary,
                biography,
                specialities,
                subSpecialities,
                languages,
                consultationModes,
                services,
                locations,
                galleryImageUrls,
                coverUrl,
                logoUrl,
                contactPhone,
                contactEmail,
                website,
                area,
                city,
                state,
                country,
                primarySpeciality,
                consultationFee,
                reviewsComingSoon,
                subtitle,
                bookingSummary,
                practices,
                clinics,
                availableDays,
                nextAvailableSlots,
                availableToday,
                null,
                false
        );
    }
}
