package com.deepthoughtnet.clinic.carepilot.campaign.service.model;

import com.deepthoughtnet.clinic.carepilot.campaign.model.AudienceType;
import com.deepthoughtnet.clinic.carepilot.campaign.model.CampaignStatus;
import com.deepthoughtnet.clinic.carepilot.campaign.model.CampaignType;
import com.deepthoughtnet.clinic.carepilot.campaign.model.TriggerType;
import java.time.OffsetDateTime;
import java.util.UUID;

/** Read model for campaign API responses. */
public record CampaignRecord(
        UUID id,
        String campaignReference,
        UUID tenantId,
        String name,
        CampaignType campaignType,
        CampaignStatus status,
        TriggerType triggerType,
        AudienceType audienceType,
        UUID templateId,
        boolean active,
        String notes,
        UUID createdBy,
        UUID submittedBy,
        String submittedByDisplayName,
        String submittedByRoleLabel,
        String submittedByEmployeeCode,
        String submittedByUsername,
        OffsetDateTime submittedAt,
        UUID reviewedBy,
        String reviewedByDisplayName,
        String reviewedByRoleLabel,
        String reviewedByEmployeeCode,
        String reviewedByUsername,
        OffsetDateTime reviewedAt,
        String reviewComment,
        UUID approvedBy,
        String approvedByDisplayName,
        String approvedByRoleLabel,
        String approvedByEmployeeCode,
        String approvedByUsername,
        OffsetDateTime approvedAt,
        UUID activationBy,
        String activationByDisplayName,
        String activationByRoleLabel,
        String activationByEmployeeCode,
        String activationByUsername,
        OffsetDateTime activationAt,
        String approvalInvalidatedReason,
        Integer approvedVersion,
        String approvedConfigurationHash,
        int version,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
) {}
