package com.deepthoughtnet.clinic.platform.contracts.ai;

public enum AiTaskType {
    CLINIC_EXTRACTION,
    CLINIC_RISK_EXPLANATION,
    DUPLICATE_EXPLANATION,
    DOCTOR_RESUBMISSION_SUGGESTION,
    RECONCILIATION_EXCEPTION_EXPLANATION,
    RECONCILIATION_MATCH_EXPLANATION,
    SUMMARY,
    GENERIC_COPILOT,
    GENERIC_CLASSIFICATION,
    GENERIC_EXTRACTION,
    GENERIC_RECOMMENDATION,
    PATIENT_HISTORY_SUMMARY,
    CLINICAL_DOCUMENT_EXTRACTION,
    CLINICAL_SUMMARY,
    CONSULTATION_NOTE_STRUCTURING,
    CONSULTATION_COPILOT,
    SYMPTOMS_DIAGNOSIS_DRAFT,
    PRESCRIPTION_TEMPLATE_SUGGESTION,
    PATIENT_INSTRUCTIONS_DRAFT,
    ALLERGY_CONDITION_WARNING
}
