package com.deepthoughtnet.clinic.platform.contracts.ai;

public enum AiTaskType {
    CLINIC_EXTRACTION,
    CLINIC_RISK_EXPLANATION,
    DUPLICATE_EXPLANATION,
    DOCTOR_RESUBMISSION_SUGGESTION,
    RECONCILIATION_EXCEPTION_EXPLANATION,
    RECONCILIATION_MATCH_EXPLANATION,
    SUMMARY,
    GENERIC_COPILOT,
    GENERIC_CLASSIFICATION,
    GENERIC_EXTRACTION,
    GENERIC_RECOMMENDATION
}
