import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();

function read(relPath) {
  return fs.readFileSync(path.join(root, relPath), "utf8");
}

test("provider controlled access resolves explicit build-time mode before dev fallback", () => {
  const config = read("src/config.ts");
  const dockerfile = read("Dockerfile");
  const compose = read("../local/docker-compose.yml");
  const composeUat = read("../local/docker-compose.uat.yml");
  const env = read("../local/.env.full-docker");
  const envExample = read("../local/.env.uat-arogia.example");

  assert.ok(config.includes('VITE_PROVIDER_PORTAL_AUTH_MODE'));
  assert.ok(config.includes('function resolveProviderPortalAuthMode(): ProviderPortalAuthMode'));
  assert.ok(config.includes('const configuredMode = normalizeProviderPortalAuthMode(import.meta.env.VITE_PROVIDER_PORTAL_AUTH_MODE);'));
  assert.ok(config.includes('if (configuredMode) {'));
  assert.ok(config.includes('return import.meta.env.DEV ? "DEV_OTP" : "OTP";'));
  assert.ok(config.includes('providerPortalAuthMode: resolveProviderPortalAuthMode()'));
  assert.ok(dockerfile.includes('ARG VITE_PROVIDER_PORTAL_AUTH_MODE='));
  assert.ok(dockerfile.includes('ENV VITE_PROVIDER_PORTAL_AUTH_MODE=${VITE_PROVIDER_PORTAL_AUTH_MODE}'));
  assert.ok(compose.includes('CLINIC_PROVIDER_PORTAL_AUTH_MODE'));
  assert.ok(compose.includes('CLINIC_PROVIDER_PORTAL_EXPOSE_DEV_OTP'));
  assert.ok(compose.includes('VITE_PROVIDER_PORTAL_AUTH_MODE'));
  assert.ok(composeUat.includes('CLINIC_PROVIDER_PORTAL_AUTH_MODE'));
  assert.ok(composeUat.includes('VITE_PROVIDER_PORTAL_AUTH_MODE'));
  assert.ok(env.includes('CLINIC_PROVIDER_PORTAL_AUTH_MODE=ACCESS_APPROVAL'));
  assert.ok(env.includes('VITE_PROVIDER_PORTAL_AUTH_MODE=ACCESS_APPROVAL'));
  assert.ok(env.includes('CLINIC_PROVIDER_PORTAL_EXPOSE_DEV_OTP=false'));
  assert.ok(envExample.includes('CLINIC_PROVIDER_PORTAL_AUTH_MODE=ACCESS_APPROVAL'));
  assert.ok(envExample.includes('VITE_PROVIDER_PORTAL_AUTH_MODE=ACCESS_APPROVAL'));
});

test("provider login and access request pages render ACCESS_APPROVAL controls only", () => {
  const loginPage = read("src/pages/provider/ProviderLoginPage.tsx");
  const accessPage = read("src/pages/provider/ProviderAccessApprovalLoginPage.tsx");
  const requestPage = read("src/pages/provider/ProviderRequestAccessPage.tsx");
  const validation = read("src/pages/provider/providerAccessValidation.ts");
  const routes = read("src/routes.ts");
  const api = read("src/api/providerAuth.ts");
  const styles = read("src/styles.css");

  assert.ok(loginPage.includes('providerPortalAuthMode === "ACCESS_APPROVAL"'));
  assert.ok(loginPage.includes("ProviderAccessApprovalLoginPage"));
  assert.ok(accessPage.includes("Friends &amp; Family access to Jeevanam Provider"));
  assert.ok(accessPage.includes("Request Provider Access"));
  assert.ok(accessPage.includes("Temporary access code"));
  assert.ok(accessPage.includes("Temporary access code <span className=\"provider-field-required\" aria-hidden=\"true\">*</span>"));
  assert.ok(accessPage.includes("Enter the 8-digit access code shared by Platform Admin after approval."));
  assert.ok(accessPage.includes("Already approved?"));
  assert.ok(accessPage.includes("returnTo"));
  assert.ok(accessPage.includes("loginProviderAccess"));
  assert.ok(accessPage.includes("getProviderLoginIdentifierError"));
  assert.ok(accessPage.includes("getProviderAccessCodeError"));
  assert.ok(accessPage.includes("sanitizeProviderAccessCodeInput"));
  assert.ok(accessPage.includes("providerLoginIdentifierHelpText"));
  assert.ok(accessPage.includes('maxLength={254}'));
  assert.ok(accessPage.includes('maxLength={8}'));
  assert.ok(requestPage.includes("Request access to Jeevanam Provider"));
  assert.ok(requestPage.includes("Submit access request"));
  assert.ok(requestPage.includes("Provider application reference"));
  assert.ok(requestPage.includes("provider-auth-form--request"));
  assert.ok(requestPage.includes("provider-auth-form-grid"));
  assert.ok(requestPage.includes("provider-auth-field--full"));
  assert.ok(requestPage.includes("Select provider type"));
  assert.ok(requestPage.includes('onFocus={() => setTouched((current) => ({ ...current, providerType: true }))}'));
  assert.ok(requestPage.includes("provider-field-required"));
  assert.ok(requestPage.includes("provider-field-optional"));
  assert.ok(requestPage.includes('maxLength={120}'));
  assert.ok(requestPage.includes('maxLength={254}'));
  assert.ok(requestPage.includes('maxLength={20}'));
  assert.ok(requestPage.includes('maxLength={80}'));
  assert.ok(requestPage.includes('maxLength={500}'));
  assert.ok(requestPage.includes('disabled={submitting || !canSubmit}'));
  assert.ok(requestPage.includes("getProviderAccessRequestFullNameError"));
  assert.ok(requestPage.includes("getProviderAccessRequestEmailError"));
  assert.ok(requestPage.includes("getProviderAccessRequestMobileError"));
  assert.ok(requestPage.includes("getProviderAccessRequestProviderTypeError"));
  assert.ok(requestPage.includes("getProviderAccessRequestReferenceError"));
  assert.ok(requestPage.includes("getProviderAccessRequestNoteError"));
  assert.ok(requestPage.includes("Your access request has been submitted. Platform Admin will review it shortly."));
  assert.ok(!requestPage.includes("Request reference:"));
  assert.ok(!requestPage.includes("submittedReference"));
  assert.ok(validation.includes("Please select a provider type."));
  assert.ok(validation.includes("PROVIDER_LOGIN_IDENTIFIER_MAX_LENGTH"));
  assert.ok(validation.includes("PROVIDER_LOGIN_ACCESS_CODE_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_FULL_NAME_MIN_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_FULL_NAME_MAX_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_EMAIL_MAX_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_MOBILE_MAX_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_PROVIDER_REFERENCE_MAX_LENGTH"));
  assert.ok(validation.includes("PROVIDER_REQUEST_NOTE_MAX_LENGTH"));
  assert.ok(validation.includes("getProviderLoginIdentifierError"));
  assert.ok(validation.includes("getProviderAccessRequestFullNameError"));
  assert.ok(validation.includes("getProviderAccessRequestProviderTypeError"));
  assert.ok(styles.includes(".provider-auth-access-layout--request"));
  assert.ok(styles.includes(".provider-auth-form--request"));
  assert.ok(styles.includes(".provider-auth-form-grid"));
  assert.ok(styles.includes(".provider-auth-field--full"));
  assert.ok(styles.includes(".provider-auth-field-error"));
  assert.ok(styles.includes(".provider-field-required"));
  assert.ok(styles.includes(".provider-field-optional"));
  assert.ok(styles.includes("grid-template-columns: minmax(0, 0.8fr) minmax(0, 1.2fr);"));
  assert.ok(styles.includes("grid-template-columns: repeat(2, minmax(0, 1fr));"));
  assert.ok(routes.includes('providerRequestAccess: { path: "/provider/request-access"'));
  assert.ok(api.includes("requestProviderAccess"));
  assert.ok(api.includes("loginProviderAccess"));

  assert.ok(!accessPage.includes("Send Verification Code"));
  assert.ok(!accessPage.includes("Development verification code"));
  assert.ok(!accessPage.includes("Resend Code"));
  assert.ok(!accessPage.includes("Verify and Continue"));
  assert.ok(!accessPage.includes("development auth tools"));
});
