package com.deepthoughtnet.clinic.api.patientportal.careai;

public enum PatientPortalCareAiAction {
    ANSWER_CONTEXT,
    ASK_MISSING_FIELD,
    ASK_CLARIFICATION,
    FIND_PROVIDER,
    FIND_PROVIDER_AVAILABILITY,
    CHECK_AVAILABILITY,
    SHOW_PROVIDER_CHOICES,
    SHOW_SLOT_CHOICES,
    SELECT_PROVIDER,
    SELECT_SLOT,
    ASK_CONFIRMATION,
    EXECUTE_PENDING_ACTION,
    REJECT_PENDING_ACTION,
    ABANDON_WORKFLOW,
    END_CONVERSATION,
    UNSUPPORTED
}
