import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

function readSource(relPath) {
  const root = fs.existsSync(path.join(process.cwd(), "src")) ? process.cwd() : path.join(process.cwd(), "web-admin");
  return fs.readFileSync(path.join(root, "src", ...relPath.split("/")), "utf8");
}

test("clinical reasoning workspace hydrates persisted reasoning on load", () => {
  const source = readSource("pages/consultations/ConsultationWorkspacePage.tsx");
  assert.ok(source.includes("clinicalReasoning.loadReasoning(consultationId)"));
  assert.ok(source.includes("!clinicalReasoning.hasLoaded"));
  assert.ok(source.includes("Loading saved reasoning..."));
  assert.ok(source.includes("Status: ${clinicalReasoningStatusLabel}"));
  assert.ok(source.includes("Generated by: ${clinicalReasoning.generatedByDisplayName}"));
  assert.ok(source.includes("Regenerate Clinical Reasoning"));
  assert.ok(source.includes("clinicalReasoning.reasoningStatus && clinicalReasoning.reasoningStatus !== \"NOT_GENERATED\""));
});

test("clinical reasoning API exposes a persisted GET endpoint", () => {
  const api = readSource("api/clinicApi.ts");
  assert.ok(api.includes("export async function getClinicalReasoning"));
  assert.ok(api.includes("/api/consultations/${consultationId}/clinical-reasoning"));
  assert.ok(api.includes("reasoningStatus?: string | null;"));
  assert.ok(api.includes("generatedByDisplayName?: string | null;"));
});

test("clinical reasoning hook preserves existing reasoning on failed regeneration", () => {
  const hook = readSource("hooks/useClinicalReasoning.ts");
  assert.ok(hook.includes("setClinicalReasoningResult(previousResult)"));
  assert.ok(hook.includes("setGeneratedByDisplayName(previousGeneratedByDisplayName)"));
  assert.ok(hook.includes("setReasoningStatus(previousReasoningStatus)"));
  assert.ok(hook.includes("loadReasoning: (consultationId: string) => Promise<ClinicalReasoningResult | null>;"));
});

test("consultation save refreshes persisted clinical reasoning after draft changes", () => {
  const source = readSource("pages/consultations/ConsultationWorkspacePage.tsx");
  assert.ok(source.includes("void clinicalReasoning.loadReasoning(merged.id);"));
});
