import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

function repoRoot() {
  return fs.existsSync(path.join(process.cwd(), "web-admin", "src")) ? path.join(process.cwd(), "web-admin") : process.cwd();
}

function readSource(relPath) {
  return fs.readFileSync(path.join(repoRoot(), "src", ...relPath.split("/")), "utf8");
}

test("patient intelligence card groups longitudinal findings and exposes review/source actions", () => {
  const card = readSource("components/clinical/PatientIntelligenceCard.tsx");
  const consultationPage = readSource("pages/consultations/ConsultationWorkspacePage.tsx");
  const mainBlock = card.split('<Drawer anchor="right"')[0];
  const drawerBlock = card.split('<Drawer anchor="right"')[1] || "";

  assert.ok(card.includes("AI Extracted Summary"));
  assert.ok(card.includes("selectLatestClinicalHighlightSource(trustedMemoryConcepts, pendingMemoryConcepts)"));
  assert.ok(card.includes("aiEnabled = true"));
  assert.ok(card.includes("patientSnapshotFallback"));
  assert.ok(card.includes("Conditions"));
  assert.ok(card.includes("Latest Labs"));
  assert.ok(card.includes("getSectionCountLabel(\"Latest Labs\""));
  assert.ok(card.includes("getSectionToggleLabel"));
  assert.ok(card.includes("shouldShowSectionToggle"));
  assert.ok(card.includes("getVisibleSectionItems"));
  assert.ok(card.includes("Risk Flags"));
  assert.ok(card.includes("Verified Findings"));
  assert.ok(card.includes("buildLatestTrustedLabProjection"));
  assert.ok(card.includes("getSectionCountLabel(\"Verified Findings\""));
  assert.ok(card.includes("View lab details"));
  assert.ok(card.includes("Pending results"));
  assert.ok(card.includes("Abnormal verified results"));
  assert.ok(card.includes("Latest report:"));
  assert.ok(card.includes("getVisibleSectionItems(structuredLabTrends, reportTrendsExpanded, 3)"));
  assert.ok(card.includes("Report Trends"));
  assert.ok(card.includes("id=\"patient-intelligence-report-trends\""));
  assert.ok(card.includes("getConsultationHistoryToggleLabel"));
  assert.ok(card.includes("shouldShowConsultationHistoryToggle"));
  assert.ok(card.includes("getVisibleConsultationHistoryItems"));
  assert.ok(card.includes("ConsultationHistoryRow"));
  assert.ok(card.includes("currentConsultation?: Consultation | null;"));
  assert.ok(card.includes("previousConsultations?: Consultation[] | null;"));
  assert.ok(card.includes("Document"));
  assert.ok(card.includes("Doctor verification required before becoming permanent patient history."));
  assert.ok(card.includes("findings pending verification"));
  assert.ok(card.includes("Across"));
  assert.ok(card.includes("Review"));
  assert.ok(!card.includes("pendingSources.length > 1 ? `${source.title} · ${source.count}`"));
  assert.ok(!card.includes("Source: {sourceDocumentTitle}"));
  assert.ok(!card.includes("sourceDocumentTitle || recentReports[0] || null"));
  assert.ok(card.includes("pendingReviewHistory || []"));
  assert.ok(card.includes("Patient intelligence becomes available after clinical documents or investigation results are added. AI-assisted summaries are currently unavailable."));
  assert.ok(card.includes("aiEnabled ? ("));
  assert.ok(card.includes("SectionBox title=\"Lab Intelligence\""));
  assert.ok(card.includes("View Source"));
  assert.ok(card.includes("Very High"));
  assert.ok(card.includes("High"));
  assert.ok(card.includes("Medium"));
  assert.ok(card.includes("Low"));
  assert.ok(card.includes("Patient Context"));
  assert.ok(card.includes("Quick patient context and operational details."));
  assert.ok(card.includes("Recent Consultations"));
  assert.ok(card.includes("drawerVisibleDocumentItems"));
  assert.ok(card.includes("No uploaded documents."));
  assert.ok(card.includes("structuredLabTrends"));
  assert.ok(card.includes("longitudinalClinicalContext?.labTrends"));
  assert.ok(card.includes("StructuredTrendLine"));
  assert.ok(card.includes("TrustedFindingRow"));
  assert.ok(card.includes("hasData ? highlightSections : ("));
  assert.ok(card.includes("sourceDocumentIds"));
  assert.ok(card.includes("join(\"-\")"));
  assert.ok(!card.includes("No radiology reports available."));
  assert.ok(!card.includes("No referral letters available."));
  assert.ok(!card.includes("No discharge summaries available."));
  assert.ok(mainBlock.includes("hasData ? highlightSections : ("));
  assert.ok(mainBlock.includes("visibleLatestLabs.map"));
  assert.ok(mainBlock.includes("visibleVerifiedFindings.map"));
  assert.ok(mainBlock.includes("visibleReportTrends.map"));
  assert.ok(mainBlock.includes("Report Trends"));
  assert.ok(!mainBlock.includes("verified analyte"));
  assert.ok(!mainBlock.includes("verified finding"));
  assert.ok(!mainBlock.includes("Current trusted latest values."));
  assert.ok(!mainBlock.includes("Trusted completed-review findings."));
  assert.ok(!mainBlock.includes("View lab details"));
  assert.ok(!mainBlock.includes("Patient Context"));
  assert.ok(drawerBlock.includes("Patient Context"));
  assert.ok(drawerBlock.includes("Quick patient context and operational details."));
  assert.ok(drawerBlock.includes("Patient Snapshot"));
  assert.ok(drawerBlock.includes("Intake status"));
  assert.ok(drawerBlock.includes("Recent Consultations"));
  assert.ok(drawerBlock.includes("drawerConsultationHistory"));
  assert.ok(drawerBlock.includes("Uploaded documents"));
  assert.ok(drawerBlock.includes("Lab Intelligence"));
  assert.ok(drawerBlock.includes("Pending results"));
  assert.ok(drawerBlock.includes("Abnormal verified results"));
  assert.ok(drawerBlock.includes("View lab details"));
  assert.ok(!drawerBlock.includes('title="Conditions"'));
  assert.ok(!drawerBlock.includes("Latest Labs"));
  assert.ok(!drawerBlock.includes("Risk Flags"));
  assert.ok(!drawerBlock.includes("Verified Findings"));
  assert.ok(!drawerBlock.includes("Report Trends"));
  assert.ok(!drawerBlock.includes("Clinical Highlights"));
  assert.ok(!drawerBlock.includes("AI Extracted Summary"));
  assert.ok(mainBlock.includes("hasData ? highlightSections : ("));
  assert.ok(consultationPage.includes("onViewSourceDocument={(documentId) => void openClinicalDocumentById(documentId)}"));
  assert.ok(consultationPage.includes("AI Clinical Assistance Unavailable"));
  assert.ok(consultationPage.includes("role=\"status\""));
});
