import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

function readSource(relPath) {
  const root = fs.existsSync(path.join(process.cwd(), "src")) ? process.cwd() : path.join(process.cwd(), "web-admin");
  return fs.readFileSync(path.join(root, "src", ...relPath.split("/")), "utf8");
}

test("patient intelligence card exposes grouped longitudinal sections", () => {
  const source = readSource("components/clinical/PatientIntelligenceCard.tsx");
  const mainBlock = source.split('<Drawer anchor="right"')[0];
  const drawerBlock = source.split('<Drawer anchor="right"')[1] || "";
  assert.ok(source.includes("Patient Intelligence"));
  assert.ok(source.includes("Patient Snapshot"));
  assert.ok(source.includes("patientSnapshotFallback"));
  assert.ok(source.includes("Clinical Highlights"));
  assert.ok(source.includes("aiEnabled = true"));
  assert.ok(source.includes("AI Extracted Summary"));
  assert.ok(source.includes("selectLatestClinicalHighlightSource"));
  assert.ok(source.includes("latestClinicalHighlightCandidate"));
  assert.ok(source.includes("sourceConcept = React.useMemo"));
  assert.ok(source.includes("pendingReviewHistory"));
  assert.ok(source.includes("Conditions"));
  assert.ok(source.includes("Latest Labs"));
  assert.ok(source.includes("getSectionCountLabel(\"Latest Labs\""));
  assert.ok(source.includes("getSectionToggleLabel"));
  assert.ok(source.includes("shouldShowSectionToggle"));
  assert.ok(source.includes("getVisibleSectionItems"));
  assert.ok(source.includes("Risk Flags"));
  assert.ok(source.includes("Verified Findings"));
  assert.ok(source.includes("buildLatestTrustedLabProjection"));
  assert.ok(source.includes("getSectionCountLabel(\"Verified Findings\""));
  assert.ok(source.includes("View lab details"));
  assert.ok(source.includes("Pending results"));
  assert.ok(source.includes("Abnormal verified results"));
  assert.ok(source.includes("Latest report:"));
  assert.ok(source.includes("getVisibleSectionItems(structuredLabTrends, reportTrendsExpanded, 3)"));
  assert.ok(source.includes("Report Trends"));
  assert.ok(source.includes("id=\"patient-intelligence-report-trends\""));
  assert.ok(source.includes("getConsultationHistoryToggleLabel"));
  assert.ok(source.includes("shouldShowConsultationHistoryToggle"));
  assert.ok(source.includes("getVisibleConsultationHistoryItems"));
  assert.ok(source.includes("ConsultationHistoryRow"));
  assert.ok(source.includes("currentConsultation?: Consultation | null;"));
  assert.ok(source.includes("previousConsultations?: Consultation[] | null;"));
  assert.ok(source.includes("Document"));
  assert.ok(source.includes("Review"));
  assert.ok(source.includes("findings pending verification"));
  assert.ok(source.includes("Across"));
  assert.ok(!source.includes("source.title} · ${source.count}"));
  assert.ok(source.includes("sourceDocumentTitle = sourceConcept?.sourceDocumentTitle || null"));
  assert.ok(source.includes("sourceConceptLabel"));
  assert.ok(source.includes("sourceConceptTone"));
  assert.ok(source.includes("sourceConceptIsPending"));
  assert.ok(source.includes("View Source"));
  assert.ok(source.includes("drawerVisibleDocumentItems"));
  assert.ok(source.includes("No uploaded documents."));
  assert.ok(source.includes("aiEnabled ? ("));
  assert.ok(source.includes("SectionBox title=\"Lab Intelligence\""));
  assert.ok(source.includes("Doctor verification required before becoming permanent patient history."));
  assert.ok(source.includes("Longitudinal patient context. Not AI generated."));
  assert.ok(source.includes("Patient intelligence becomes available after clinical documents or investigation results are added. AI-assisted summaries are currently unavailable."));
  assert.ok(source.includes("structuredLabTrends"));
  assert.ok(source.includes("longitudinalClinicalContext?.labTrends"));
  assert.ok(source.includes("StructuredTrendLine"));
  assert.ok(source.includes("TrustedFindingRow"));
  assert.ok(source.includes("sourceDocumentIds"));
  assert.ok(source.includes("clinicalInterpretation"));
  assert.ok(source.includes("join(\"-\")"));
  assert.ok(source.includes("hasData ? highlightSections : ("));
  assert.ok(!source.includes("No radiology reports available."));
  assert.ok(!source.includes("No referral letters available."));
  assert.ok(!source.includes("No discharge summaries available."));
  assert.ok(source.includes("Very High"));
  assert.ok(source.includes("High"));
  assert.ok(source.includes("Medium"));
  assert.ok(source.includes("Low"));
  assert.ok(source.includes("resolveTrustedLabStatus"));
  assert.ok(source.includes("Patient Context"));
  assert.ok(source.includes("Quick patient context and operational details."));
  assert.ok(source.includes("Recent Consultations"));

  assert.ok(mainBlock.includes("hasData ? highlightSections : ("));
  assert.ok(mainBlock.includes("visibleLatestLabs.map"));
  assert.ok(mainBlock.includes("visibleVerifiedFindings.map"));
  assert.ok(mainBlock.includes("visibleReportTrends.map"));
  assert.ok(mainBlock.includes("Report Trends"));
  assert.ok(mainBlock.includes('label="Long-term Medications"'));
  assert.ok(mainBlock.includes('medications.map((item) => item.label).join(", ")'));
  assert.ok(!mainBlock.includes("currentMedications.slice(0, 3).join(\", \")"));
  assert.ok(!mainBlock.includes("snapshotCurrentMedications.slice(0, 3).join(\", \")"));
  assert.ok(!mainBlock.includes("verified analyte"));
  assert.ok(!mainBlock.includes("verified finding"));
  assert.ok(!mainBlock.includes("Current trusted latest values."));
  assert.ok(!mainBlock.includes("Trusted completed-review findings."));
  assert.ok(!mainBlock.includes("View lab details"));
  assert.ok(!mainBlock.includes("Patient Context"));
  assert.ok(drawerBlock.includes("Patient Context"));
  assert.ok(drawerBlock.includes("Quick patient context and operational details."));
  assert.ok(drawerBlock.includes("Patient Snapshot"));
  assert.ok(drawerBlock.includes("Intake status"));
  assert.ok(drawerBlock.includes("Recent Consultations"));
  assert.ok(drawerBlock.includes("drawerConsultationHistory"));
  assert.ok(drawerBlock.includes("Uploaded documents"));
  assert.ok(drawerBlock.includes("Lab Intelligence"));
  assert.ok(drawerBlock.includes("Pending results"));
  assert.ok(drawerBlock.includes("Abnormal verified results"));
  assert.ok(drawerBlock.includes("View lab details"));
  assert.ok(!drawerBlock.includes('title="Conditions"'));
  assert.ok(!drawerBlock.includes("Latest Labs"));
  assert.ok(!drawerBlock.includes("Risk Flags"));
  assert.ok(!drawerBlock.includes("Verified Findings"));
  assert.ok(!drawerBlock.includes("Report Trends"));
  assert.ok(!drawerBlock.includes("Clinical Highlights"));
  assert.ok(!drawerBlock.includes("AI Extracted Summary"));
});
