import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

function readSource(relPath) {
  const root = fs.existsSync(path.join(process.cwd(), "src")) ? process.cwd() : path.join(process.cwd(), "web-admin");
  return fs.readFileSync(path.join(root, "src", ...relPath.split("/")), "utf8");
}

test("consultation prescription tab exposes prescription intelligence surfaces", () => {
  const source = readSource("pages/consultations/ConsultationWorkspacePage.tsx");
  assert.ok(!source.includes("window.confirm"));
  assert.ok(!source.includes("window.prompt"));
  assert.ok(!source.includes("window.alert"));
  assert.ok(source.includes("Search Medicine → Prescribe → Safety Review → Preview → Finalize"));
  assert.ok(source.indexOf("Active Prescription") < source.indexOf("Prescription summary"));
  assert.ok(source.includes("Smart medicine suggestions"));
  assert.ok(source.includes("Suggest medicines with AIVA"));
  assert.ok(source.includes("Prescription Quality Checklist"));
  assert.ok(source.includes("Dose specified"));
  assert.ok(source.includes("Duration specified"));
  assert.ok(source.includes("Prescription Intelligence"));
  assert.ok(source.includes("Safety"));
  assert.ok(source.includes("Comparison"));
  assert.ok(source.includes("Instructions"));
  assert.ok(source.includes("Summary"));
  assert.ok(source.includes("Clinical medication suggestions will appear here when enough diagnosis, allergy, and medication context is available."));
  assert.ok(source.includes("View details"));
  assert.ok(source.includes("Safety:"));
  assert.ok(source.includes("Prescription Intelligence"));
  assert.ok(source.includes("Comparison"));
  assert.ok(source.includes("No previous finalized prescription available for comparison."));
  assert.ok(source.includes("Patient instructions"));
  assert.ok(source.includes("Generate patient instructions"));
  assert.ok(source.includes("No instructions generated yet. Choose a language and generate patient-friendly instructions."));
  assert.ok(source.includes("Prescription summary"));
  assert.ok(source.includes("Generate Prescription Summary"));
  assert.ok(source.includes("Use for WhatsApp message"));
  assert.ok(source.includes("Use for Email message"));
  assert.ok(source.includes("Alternatives"));
  assert.ok(source.includes("No alternative data available."));
  assert.ok(source.includes("AI medication suggestions are assistive. Doctor must verify before prescribing."));
  assert.ok(source.includes("English"));
  assert.ok(source.includes("Hindi"));
  assert.ok(source.includes("Marathi"));
  assert.ok(source.includes("1. Choose language"));
  assert.ok(source.includes("Frequently Used"));
  assert.ok(source.includes("Favorites"));
  assert.ok(source.includes("All Medicines"));
  assert.ok(source.includes("Favorite Packs"));
  assert.ok(source.includes("Recent Packs"));
  assert.ok(source.includes("Clinic Templates"));
  assert.ok(source.includes("AI Suggested"));
  assert.ok(source.includes("Previous Medicines"));
  assert.ok(source.includes("Route"));
  assert.ok(source.includes("Frequency"));
  assert.ok(source.includes("Duration"));
  assert.ok(source.includes("Timing"));
  assert.ok(source.includes("Continued medicines:"));
  assert.ok(source.includes("Stopped medicines:"));
  assert.ok(source.includes("New medicines:"));
  assert.ok(source.includes("Not enough data"));
  assert.ok(source.includes("Accept"));
  assert.ok(source.includes("Edit"));
  assert.ok(source.includes("Reject"));
  assert.ok(source.includes("Copy"));
  assert.ok(source.includes("Dose changes:"));
  assert.ok(source.includes("No finalized prescriptions yet. Once finalized, every version will be stored here for medico-legal audit."));
  assert.ok(source.includes("Finalized versions stay immutable and traceable."));
  assert.ok(source.includes("Replace Prescription Draft?"));
  assert.ok(source.includes("Apply Fast Pack"));
});
