import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

function readSource(relPath) {
  const root = fs.existsSync(path.join(process.cwd(), "src")) ? process.cwd() : path.join(process.cwd(), "web-admin");
  return fs.readFileSync(path.join(root, "src", ...relPath.split("/")), "utf8");
}

test("provider connections console is routed, gated, and linked from platform navigation", () => {
  const app = readSource("app/App.tsx");
  const nav = readSource("layout/nav.ts");
  const sidebar = readSource("layout/SidebarNav.tsx");
  const registry = readSource("modules/moduleRegistry.ts");
  const page = readSource("pages/platform/ProviderConnectionsPage.tsx");
  const api = readSource("api/clinicApi.ts");
  const permissions = readSource("auth/permissions.ts");

  assert.ok(app.includes('path="/platform/provider-connections/*"'));
  assert.ok(app.includes("ProviderConnectionsPage"));
  assert.ok(nav.includes('path: "/platform/provider-connections"'));
  assert.ok(nav.includes('label: "Provider Connections"'));
  assert.ok(sidebar.includes("platform-provider-connections"));
  assert.ok(registry.includes('path === "/platform/provider-connections"'));
  assert.ok(registry.includes('path.startsWith("/platform/provider-connections/")'));
  assert.ok(page.includes("Provider Connections"));
  assert.ok(page.includes("Public Profiles"));
  assert.ok(page.includes("Public Profile Reviews"));
  assert.ok(page.includes("Platform Entities"));
  assert.ok(page.includes("Suggested Matches"));
  assert.ok(page.includes("Conflicts"));
  assert.ok(page.includes("Audit"));
  assert.ok(page.includes("ADD_REVIEW_FINDING"));
  assert.ok(page.includes("Add finding"));
  assert.ok(page.includes("Reconcile"));
  assert.ok(page.includes("Review match"));
  assert.ok(page.includes("Reject suggestion"));
  assert.ok(page.includes("Propose link"));
  assert.ok(page.includes("You are reviewing the exact profile version submitted by the Provider."));
  assert.ok(page.includes('section !== "public-profile-reviews" ?'));
  assert.ok(page.includes('selectedPublicProfileReference'));
  assert.ok(page.includes('selectedPlatformEntityReference'));
  assert.ok(page.includes('selectedSuggestionKey'));
  assert.ok(page.includes('selectedLinkReference'));
  assert.ok(page.includes('selectedOwnershipReference'));
  assert.ok(page.includes('selectedAuditEventReference'));
  assert.ok(page.includes("Public Profile Details"));
  assert.ok(page.includes("Platform Entity Details"));
  assert.ok(page.includes("Suggestion Details"));
  assert.ok(page.includes("Link Details"));
  assert.ok(page.includes("Ownership Details"));
  assert.ok(page.includes("Audit Event Details"));
  assert.ok(page.includes("Conflict Details"));
  assert.ok(page.includes("Operational Clinic"));
  assert.ok(page.includes("Technical Details"));
  assert.ok(page.includes("Public URL"));
  assert.ok(!page.includes('Pick a row from Links to inspect a specific link.'));
  assert.ok(api.includes("getProviderConnectionsOverview"));
  assert.ok(api.includes("listProviderConnectionsPublicProfiles"));
  assert.ok(api.includes("listProviderConnectionsPublicPractices"));
  assert.ok(api.includes("listProviderConnectionsPlatformEntities"));
  assert.ok(api.includes("listProviderConnectionsLinks"));
  assert.ok(api.includes("listProviderConnectionsSuggestions"));
  assert.ok(api.includes("listProviderConnectionsConflicts"));
  assert.ok(api.includes("getProviderConnectionsAuditEvents"));
  assert.ok(api.includes("rejectProviderConnectionSuggestion"));
  assert.ok(api.includes("proposeProviderConnectionLink"));
  assert.ok(api.includes("approveProviderConnectionLink"));
  assert.ok(api.includes("activateProviderConnectionLink"));
  assert.ok(api.includes("unlinkProviderConnectionLink"));
  assert.ok(api.includes("relinkProviderConnectionLink"));
  assert.ok(api.includes("rejectProviderConnectionLink"));
  assert.ok(api.includes("suspendProviderConnectionLink"));
  assert.ok(api.includes("resumeProviderConnectionLink"));
  assert.ok(api.includes("reconcileProviderConnection"));
  assert.ok(page.includes('selectedLink.allowedActions.includes("VERIFY_LINK")'));
  assert.ok(page.includes('selectedLink.allowedActions.includes("ACTIVATE_LINK")'));
  assert.ok(page.includes('selectedLink.allowedActions.includes("DISCONNECT_LINK")'));
  assert.ok(!page.includes('selectedLink.linkStatus === "APPROVED"'));
  assert.ok(permissions.includes("platform.provider_connection.view"));
  assert.ok(permissions.includes("platform.provider_connection.propose"));
  assert.ok(permissions.includes("platform.provider_connection.approve"));
  assert.ok(permissions.includes("platform.provider_connection.unlink"));
  assert.ok(permissions.includes("platform.provider_connection.reconcile"));
  assert.ok(permissions.includes("platform.provider_connection.audit"));
});
