package com.deepthoughtnet.clinic.platform.branding;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "branding")
public class BrandingProperties {
    private String productName = "Arogia";
    private String tagline = "Smart Healthcare Management Platform";
    private String companyName = "DeepThoughtNet";
    private String aiPlatformName = "AIVA";

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        if (productName != null && !productName.isBlank()) {
            this.productName = productName;
        }
    }

    public String getTagline() {
        return tagline;
    }

    public void setTagline(String tagline) {
        if (tagline != null && !tagline.isBlank()) {
            this.tagline = tagline;
        }
    }

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        if (companyName != null && !companyName.isBlank()) {
            this.companyName = companyName;
        }
    }

    public String getAiPlatformName() {
        return aiPlatformName;
    }

    public void setAiPlatformName(String aiPlatformName) {
        if (aiPlatformName != null && !aiPlatformName.isBlank()) {
            this.aiPlatformName = aiPlatformName;
        }
    }

    public String productAndTagline() {
        return productName + " | " + tagline;
    }

    public String footerLine() {
        return "Generated by " + productName + " | Powered by " + aiPlatformName;
    }
}
